name: tracksu
description: Flutter project disgned for tracking and analyzing osu! statisics provided by osu! API

publish_to: 'none'

version: 1.2.0+6

environment:
  sdk: ">=2.18.2 <3.3.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  url_launcher: ^6.1.8
  cupertino_icons: ^1.0.5
  cached_network_image: ^3.2.3
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  flutter_secure_storage: ^7.0.1
  flutter_launcher_icons: ^0.10.0
  webview_flutter: ^3.0.4
  audioplayers: ^1.1.1
  curved_navigation_bar: ^1.0.3
  flutter_widget_from_html: ^0.9.1
  fluttericon: ^2.0.0
  intl: ^0.18.0
  flutter_native_splash: ^2.2.13

flutter_native_splash:
  image: "assets/utils/painted_logo.png"
  color: "221919"

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/utils/painted_logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/icon_mods/
    - assets/icon_pack/
    - assets/icon_game_mods/
    - assets/icon_country_flags/
    - assets/icon_score_types/
    - assets/utils/
    - assets/models/

  fonts:
    - family: Exo 2
      fonts:
        - asset: assets/fonts/Exo2-VariableFont_wght.ttf
        - asset: assets/fonts/Exo2-italic-VariableFont_wght.ttf
          style: italic
    - family:  MyFlutterApp
      fonts:
        - asset: assets/icon_pack/MyFlutterApp.ttf