name: osu_track_app
description: Flutter project disgned for tracking and analyzing osu! statisics provided by osu! API

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <=3.2.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  url_launcher: ^6.0.12
  flutter_webview_plugin: ^0.4.0
  cupertino_icons: ^1.0.3
  cached_network_image: ^3.1.0
  bloc: ^7.2.1
  flutter_bloc: ^7.3.1
  flutter_secure_storage: ^4.2.1
  country_icons: ^2.0.2
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/painted_logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/icon_mods/
    - assets/icon_pack/
    - assets/icon_score_types/
    - assets/utils/

  fonts:
    - family: Exo 2
      fonts:
        - asset: assets/fonts/Exo2-VariableFont_wght.ttf
        - asset: assets/fonts/Exo2-italic-VariableFont_wght.ttf
          style: italic
    - family:  MyFlutterApp
      fonts:
        - asset: assets/icon_pack/MyFlutterApp.ttf